version: "3"
services:

  server1:
    #TODO Comment out in favor of build context below
    # image: kjertis/get-started:part2
    #TODO Add the build context
    context: 
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
  
  server2:
    #TODO Add the build context
    context:

networks:
  webnet:
